language: node_js
node_js:
- 10.15.3
cache:
  directories:
  - node_modules
global:
 - export NODE_ENV=test

env:
  global:
    - CC_TEST_REPORTER_ID=57c3047d5def5222f8221b8a3d6e52e0c6939241f014ee469a23b3f8d4142eea

before_install:
- npm install

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  
after_success:
- npm run coverage

script:
- npm run test
